version: "3.9"

services:
  supernode:
    build: ./server
    container_name: fl_supernode
    ports:
      - "8080:8080"  # gRPC / Flower server
      - "8081:8081"  # dashboard
    environment:
      - FLOWER_DASHBOARD_PORT=8081
    volumes:
      - ./server/data:/app/data

  client1:
    build: ./client
    container_name: fl_client1
    depends_on:
      - supernode
    environment:
      - ALGO=LSTM
    command: python client.py --server_address fl_supernode:8080
    volumes:
      - ./dataset_sdn.csv:/app/dataset_sdn.csv

  client2:
    build: ./client
    container_name: fl_client2
    depends_on:
      - supernode
    environment:
      - ALGO=LSTM
    command: python client.py --server_address fl_supernode:8080
    volumes:
      - ./dataset_sdn.csv:/app/dataset_sdn.csv
